import os

def compile_ui():
    ui_dir = os.path.join(os.path.dirname(__file__), 'ui')
    src_dir = os.path.join(os.path.dirname(__file__), 'src')
    
    html_path = os.path.join(ui_dir, 'index.html')
    css_path = os.path.join(ui_dir, 'style.css')
    js_path = os.path.join(ui_dir, 'app.js')
    
    if not os.path.exists(html_path) or not os.path.exists(css_path) or not os.path.exists(js_path):
        print("Error: Missing UI source files.")
        return
        
    with open(html_path, 'r', encoding='utf-8') as f:
        html = f.read()
        
    with open(css_path, 'r', encoding='utf-8') as f:
        css = f.read()
        
    with open(js_path, 'r', encoding='utf-8') as f:
        js = f.read()
        
    # Inline CSS
    css_tag = '<link rel="stylesheet" href="style.css">'
    inlined_css = f'<style>\n{css}\n</style>'
    html = html.replace(css_tag, inlined_css)
    
    # Inline JS
    js_tag = '<script src="app.js"></script>'
    inlined_js = f'<script>\n{js}\n</script>'
    html = html.replace(js_tag, inlined_js)
    
    # Write to C++ header
    output_path = os.path.join(src_dir, 'inlined_html.hpp')
    
    header_content = f"""#ifndef INLINED_HTML_HPP
#define INLINED_HTML_HPP

// Auto-generated by ui_compiler.py - DO NOT MODIFY DIRECTLY
const char* const CHEAT_UI_HTML = R"html(
{html}
)html";

#endif // INLINED_HTML_HPP
"""
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(header_content)
        
    print(f"Successfully compiled UI to {output_path}")

if __name__ == '__main__':
    compile_ui()
