#ifndef INLINED_HTML_HPP
#define INLINED_HTML_HPP

// Auto-generated by ui_compiler.py - DO NOT MODIFY DIRECTLY
const char* const CHEAT_UI_HTML = R"html(
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <title>Antigravity Engine</title>
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;600;800&family=JetBrains+Mono:wght@400;700&display=swap" rel="stylesheet">
    <style>
:root {
    --bg-color: rgba(10, 10, 14, 0.75);
    --border-color: rgba(255, 255, 255, 0.08);
    --text-primary: #f0f2f5;
    --text-secondary: #9aa0a6;
    --accent-cyan: #00f0ff;
    --accent-purple: #9d4edd;
    --accent-gold: #ffb700;
    --accent-danger: #ff4d4d;
    --panel-shadow: 0 8px 32px 0 rgba(0, 0, 0, 0.4);
    --font-sans: 'Outfit', sans-serif;
    --font-mono: 'JetBrains Mono', monospace;
    --glass-blur: 20px;
}

* {
    box-sizing: border-box;
    margin: 0;
    padding: 0;
    user-select: none;
    -webkit-user-select: none;
    -webkit-tap-highlight-color: transparent;
}

body {
    font-family: var(--font-sans);
    background: transparent;
    color: var(--text-primary);
    overflow: hidden;
    width: 100vw;
    height: 100vh;
    display: flex;
    justify-content: center;
    align-items: center;
    padding: 10px;
}

/* Glassmorphic Container */
.glass-container {
    width: 100%;
    height: 100%;
    max-width: 760px;
    max-height: 480px;
    background: var(--bg-color);
    border: 1px solid var(--border-color);
    border-radius: 18px;
    backdrop-filter: blur(var(--glass-blur));
    -webkit-backdrop-filter: blur(var(--glass-blur));
    box-shadow: var(--panel-shadow);
    display: flex;
    flex-direction: column;
    overflow: hidden;
    animation: scaleUp 0.3s cubic-bezier(0.16, 1, 0.3, 1);
}

@keyframes scaleUp {
    from {
        opacity: 0;
        transform: scale(0.96);
    }
    to {
        opacity: 1;
        transform: scale(1);
    }
}

/* Header styling */
.app-header {
    height: 52px;
    border-bottom: 1px solid var(--border-color);
    padding: 0 16px;
    display: flex;
    justify-content: space-between;
    align-items: center;
    background: rgba(255, 255, 255, 0.02);
}

.logo-area {
    display: flex;
    align-items: center;
    gap: 8px;
}

.pulse-dot {
    width: 8px;
    height: 8px;
    background-color: var(--accent-cyan);
    border-radius: 50%;
    box-shadow: 0 0 8px var(--accent-cyan);
    animation: pulse 1.8s infinite;
}

@keyframes pulse {
    0% { transform: scale(0.9); opacity: 0.6; }
    50% { transform: scale(1.15); opacity: 1; box-shadow: 0 0 12px var(--accent-cyan); }
    100% { transform: scale(0.9); opacity: 0.6; }
}

.logo-area h1 {
    font-size: 16px;
    font-weight: 800;
    letter-spacing: 2px;
    background: linear-gradient(135deg, #ffffff, #888888);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
}

.badge {
    font-size: 10px;
    font-weight: 600;
    color: var(--accent-cyan);
    background: rgba(0, 240, 255, 0.1);
    padding: 2px 6px;
    border-radius: 4px;
    border: 1px solid rgba(0, 240, 255, 0.2);
}

.close-btn {
    background: transparent;
    border: none;
    color: var(--text-secondary);
    font-size: 24px;
    font-weight: 300;
    cursor: pointer;
    transition: color 0.2s, transform 0.2s;
    width: 32px;
    height: 32px;
    display: flex;
    justify-content: center;
    align-items: center;
}

.close-btn:hover {
    color: var(--accent-danger);
    transform: scale(1.1);
}

/* Panel Layout */
.main-panel {
    flex: 1;
    display: flex;
    overflow: hidden;
}

/* Sidebar */
.sidebar {
    width: 70px;
    border-right: 1px solid var(--border-color);
    background: rgba(0, 0, 0, 0.15);
    display: flex;
    flex-direction: column;
    align-items: center;
    padding: 16px 0;
    gap: 16px;
}

.nav-item {
    background: transparent;
    border: none;
    width: 50px;
    height: 50px;
    border-radius: 12px;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    gap: 4px;
    cursor: pointer;
    color: var(--text-secondary);
    transition: all 0.25s ease;
}

.nav-item span {
    font-size: 8px;
    font-weight: 500;
}

.nav-item .icon {
    width: 20px;
    height: 20px;
    fill: currentColor;
}

.nav-item:hover {
    color: var(--text-primary);
    background: rgba(255, 255, 255, 0.04);
}

.nav-item.active {
    color: var(--accent-cyan);
    background: rgba(0, 240, 255, 0.08);
    box-shadow: inset 0 0 10px rgba(0, 240, 255, 0.05);
    border: 1px solid rgba(0, 240, 255, 0.15);
}

/* Content Area */
.content {
    flex: 1;
    overflow: hidden;
    position: relative;
    padding: 16px;
}

.tab-content {
    display: none;
    height: 100%;
    flex-direction: column;
    animation: fadeIn 0.25s ease;
}

.tab-content.active {
    display: flex;
}

@keyframes fadeIn {
    from { opacity: 0; transform: translateY(4px); }
    to { opacity: 1; transform: translateY(0); }
}

/* Form Styling */
.scan-controls {
    display: flex;
    gap: 12px;
    margin-bottom: 12px;
    align-items: flex-end;
}

.input-group {
    display: flex;
    flex-direction: column;
    gap: 6px;
    flex: 1;
}

label {
    font-size: 11px;
    font-weight: 600;
    color: var(--text-secondary);
    text-transform: uppercase;
    letter-spacing: 0.5px;
}

input[type="text"], select, input[type="number"] {
    width: 100%;
    height: 38px;
    background: rgba(255, 255, 255, 0.03);
    border: 1px solid var(--border-color);
    border-radius: 8px;
    color: var(--text-primary);
    padding: 0 12px;
    font-family: var(--font-sans);
    font-size: 13px;
    outline: none;
    transition: all 0.2s ease;
}

input[type="text"]:focus, select:focus, input[type="number"]:focus {
    border-color: rgba(0, 240, 255, 0.4);
    background: rgba(255, 255, 255, 0.05);
    box-shadow: 0 0 8px rgba(0, 240, 255, 0.15);
}

select {
    cursor: pointer;
    appearance: none;
    background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='12' fill='%239aa0a6' viewBox='0 0 24 24'%3E%3Cpath d='M7 10l5 5 5-5z'/%3E%3C/svg%3E");
    background-repeat: no-repeat;
    background-position: right 12px center;
    padding-right: 28px;
}

/* Buttons */
.button-row {
    display: flex;
    gap: 8px;
}

.btn {
    height: 38px;
    padding: 0 16px;
    border-radius: 8px;
    font-size: 13px;
    font-weight: 600;
    cursor: pointer;
    transition: all 0.2s ease;
    border: none;
    display: inline-flex;
    justify-content: center;
    align-items: center;
    gap: 6px;
}

.btn-primary {
    background: linear-gradient(135deg, var(--accent-cyan), #00a8ff);
    color: #050508;
    box-shadow: 0 2px 10px rgba(0, 240, 255, 0.25);
}

.btn-primary:hover:not(:disabled) {
    transform: translateY(-1px);
    box-shadow: 0 4px 14px rgba(0, 240, 255, 0.35);
}

.btn-secondary {
    background: rgba(255, 255, 255, 0.06);
    border: 1px solid var(--border-color);
    color: var(--text-primary);
}

.btn-secondary:hover:not(:disabled) {
    background: rgba(255, 255, 255, 0.1);
}

.btn-danger {
    background: rgba(255, 77, 77, 0.15);
    border: 1px solid rgba(255, 77, 77, 0.2);
    color: var(--accent-danger);
}

.btn-danger:hover:not(:disabled) {
    background: rgba(255, 77, 77, 0.25);
}

.btn-small {
    height: 28px;
    padding: 0 10px;
    border-radius: 6px;
    font-size: 11px;
}

.btn:disabled {
    opacity: 0.35;
    cursor: not-allowed;
    transform: none !important;
    box-shadow: none !important;
}

/* Status Panel */
.scan-status {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 8px 12px;
    background: rgba(0, 0, 0, 0.2);
    border-radius: 8px;
    margin-bottom: 12px;
    font-size: 12px;
    color: var(--text-secondary);
}

.loader {
    width: 14px;
    height: 14px;
    border: 2px solid rgba(0, 240, 255, 0.2);
    border-top-color: var(--accent-cyan);
    border-radius: 50%;
    animation: spin 0.6s linear infinite;
}

@keyframes spin {
    to { transform: rotate(360deg); }
}

.hidden {
    display: none !important;
}

/* Results Table */
.results-container {
    flex: 1;
    overflow-y: auto;
    border: 1px solid var(--border-color);
    border-radius: 8px;
    background: rgba(0, 0, 0, 0.12);
}

.results-table {
    width: 100%;
    border-collapse: collapse;
    font-size: 13px;
    text-align: left;
}

.results-table th {
    background: rgba(255, 255, 255, 0.02);
    padding: 10px 14px;
    font-weight: 600;
    font-size: 11px;
    color: var(--text-secondary);
    text-transform: uppercase;
    border-bottom: 1px solid var(--border-color);
}

.results-table td {
    padding: 8px 14px;
    border-bottom: 1px solid rgba(255, 255, 255, 0.03);
    vertical-align: middle;
}

.results-table tr:hover {
    background: rgba(255, 255, 255, 0.02);
}

.placeholder-row {
    text-align: center;
    color: var(--text-secondary);
    padding: 40px !important;
}

.addr-col {
    font-family: var(--font-mono);
    color: var(--accent-gold);
    font-weight: 600;
}

.val-col {
    font-family: var(--font-mono);
}

.action-cell {
    display: flex;
    gap: 6px;
}

/* Lock Icon button */
.lock-btn {
    background: transparent;
    border: none;
    color: var(--text-secondary);
    cursor: pointer;
    padding: 4px;
    border-radius: 4px;
    transition: all 0.2s;
}

.lock-btn.locked {
    color: var(--accent-cyan);
    filter: drop-shadow(0 0 3px rgba(0, 240, 255, 0.4));
}

.lock-btn svg {
    width: 16px;
    height: 16px;
    fill: currentColor;
}

/* Speed Hack Tab Layout */
.speed-panel {
    display: flex;
    height: 100%;
    align-items: center;
    justify-content: center;
    gap: 40px;
    padding: 20px;
}

.gauge-container {
    flex: 1;
    display: flex;
    justify-content: center;
    align-items: center;
}

.gauge {
    position: relative;
    width: 160px;
    height: 160px;
}

.gauge-body {
    width: 100%;
    height: 100%;
    border-radius: 50%;
    background: rgba(255, 255, 255, 0.03);
    border: 6px solid var(--border-color);
    position: relative;
    display: flex;
    justify-content: center;
    align-items: center;
    box-shadow: inset 0 0 20px rgba(0, 0, 0, 0.6);
}

.gauge-fill {
    position: absolute;
    top: -6px; left: -6px; right: -6px; bottom: -6px;
    border-radius: 50%;
    border: 6px solid transparent;
    border-top-color: var(--accent-cyan);
    border-right-color: var(--accent-cyan);
    transform: rotate(-45deg);
    transition: transform 0.2s cubic-bezier(0.1, 0.8, 0.3, 1);
    filter: drop-shadow(0 0 6px rgba(0, 240, 255, 0.4));
}

.gauge-cover {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    z-index: 2;
}

#speed-val {
    font-size: 38px;
    font-weight: 800;
    font-family: var(--font-mono);
    color: var(--text-primary);
    text-shadow: 0 0 10px rgba(255, 255, 255, 0.1);
}

.speed-unit {
    font-size: 12px;
    font-weight: 700;
    color: var(--accent-cyan);
    text-transform: uppercase;
}

.speed-controls {
    flex: 1;
    display: flex;
    flex-direction: column;
    gap: 20px;
    width: 100%;
}

.slider-wrapper {
    display: flex;
    align-items: center;
    gap: 12px;
    width: 100%;
}

.speed-limit {
    font-size: 11px;
    color: var(--text-secondary);
    font-weight: 600;
}

input[type="range"] {
    flex: 1;
    -webkit-appearance: none;
    background: rgba(255, 255, 255, 0.05);
    height: 6px;
    border-radius: 3px;
    outline: none;
    border: 1px solid var(--border-color);
}

input[type="range"]::-webkit-slider-thumb {
    -webkit-appearance: none;
    width: 18px;
    height: 18px;
    border-radius: 50%;
    background: var(--accent-cyan);
    box-shadow: 0 0 8px var(--accent-cyan);
    cursor: pointer;
    transition: transform 0.1s;
}

input[type="range"]::-webkit-slider-thumb:active {
    transform: scale(1.2);
}

.fine-tune {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 8px;
}

#speed-input {
    width: 80px;
    text-align: center;
    font-family: var(--font-mono);
    font-size: 15px;
    font-weight: 700;
}

/* Modals */
.modal-overlay {
    position: fixed;
    top: 0; left: 0; right: 0; bottom: 0;
    background: rgba(5, 5, 8, 0.6);
    backdrop-filter: blur(5px);
    -webkit-backdrop-filter: blur(5px);
    display: flex;
    justify-content: center;
    align-items: center;
    z-index: 100;
    animation: fadeIn 0.2s ease;
}

.glass-modal {
    background: rgba(20, 20, 28, 0.85);
    border: 1px solid var(--border-color);
    border-radius: 16px;
    padding: 20px;
    width: 280px;
    box-shadow: var(--panel-shadow);
    display: flex;
    flex-direction: column;
    gap: 16px;
}

.glass-modal h3 {
    font-size: 16px;
    font-weight: 700;
    text-align: center;
}

.address-display {
    font-family: var(--font-mono);
    text-align: center;
    font-size: 14px;
    color: var(--accent-gold);
    background: rgba(255, 183, 0, 0.05);
    border: 1px solid rgba(255, 183, 0, 0.15);
    padding: 6px;
    border-radius: 6px;
}

.modal-buttons {
    display: flex;
    justify-content: flex-end;
    gap: 8px;
}

</style>
</head>
<body>
    <div class="glass-container">
        <!-- Header -->
        <header class="app-header">
            <div class="logo-area">
                <span class="pulse-dot"></span>
                <h1>ANTIGRAVITY</h1>
                <span class="badge">V1.0</span>
            </div>
            <button class="close-btn" id="btn-close-ui">×</button>
        </header>

        <!-- Main Panel -->
        <div class="main-panel">
            <!-- Sidebar -->
            <nav class="sidebar">
                <button class="nav-item active" data-target="tab-memory">
                    <svg class="icon" viewBox="0 0 24 24"><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 15h-2v-6h2v6zm0-8h-2V7h2v2z"/></svg>
                    <span>Memory</span>
                </button>
                <button class="nav-item" data-target="tab-speed">
                    <svg class="icon" viewBox="0 0 24 24"><path d="M20.38 8.57l-1.23 1.85a8 8 0 0 1-.22 7.58H5.07A8 8 0 0 1 12 6a8 8 0 0 1 5.3 2l1.24-1.87A10 10 0 0 0 3 16.58a10 10 0 0 0 18 0 10 10 0 0 0-.62-8.01zM10.3 12.3a2 2 0 0 0 2.83 0l4.24-4.24-1.41-1.42-4.24 4.24a2 2 0 0 0-1.42 1.42z"/></svg>
                    <span>Speedhack</span>
                </button>
            </nav>

            <!-- Content Area -->
            <main class="content">
                <!-- Tab: Memory Scanner -->
                <section id="tab-memory" class="tab-content active">
                    <div class="scan-controls">
                        <div class="input-group">
                            <label for="select-type">Data Type</label>
                            <select id="select-type">
                                <option value="i32">32-bit Integer (i32)</option>
                                <option value="i64">64-bit Integer (i64)</option>
                                <option value="float">Float (float)</option>
                                <option value="double">Double (double)</option>
                            </select>
                        </div>
                        <div class="input-group">
                            <label for="input-value">Search Value</label>
                            <div class="search-input-wrapper">
                                <input type="text" id="input-value" placeholder="Enter value..." inputmode="decimal">
                            </div>
                        </div>
                        <div class="button-row">
                            <button id="btn-first-scan" class="btn btn-primary">First Scan</button>
                            <button id="btn-next-scan" class="btn btn-secondary" disabled>Next Scan</button>
                            <button id="btn-clear" class="btn btn-danger">Clear</button>
                        </div>
                    </div>

                    <div class="scan-status">
                        <span id="status-text">Ready to Scan</span>
                        <div id="loader" class="loader hidden"></div>
                    </div>

                    <div class="results-container">
                        <table class="results-table">
                            <thead>
                                <tr>
                                    <th>Address</th>
                                    <th>Value</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody id="results-body">
                                <tr>
                                    <td colspan="3" class="placeholder-row">No results. Perform a scan.</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </section>

                <!-- Tab: Speed Hack -->
                <section id="tab-speed" class="tab-content">
                    <div class="speed-panel">
                        <div class="gauge-container">
                            <div class="gauge">
                                <div class="gauge-body">
                                    <div class="gauge-fill" id="speed-fill"></div>
                                    <div class="gauge-cover">
                                        <span id="speed-val">1.0</span>
                                        <span class="speed-unit">x</span>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="speed-controls">
                            <div class="slider-wrapper">
                                <span class="speed-limit">0.1x</span>
                                <input type="range" id="speed-slider" min="0.1" max="20" step="0.1" value="1.0">
                                <span class="speed-limit">20.0x</span>
                            </div>
                            
                            <div class="fine-tune">
                                <button class="btn btn-small" id="btn-speed-dec">-0.1</button>
                                <input type="number" id="speed-input" min="0.1" max="100" step="0.1" value="1.0">
                                <button class="btn btn-small" id="btn-speed-inc">+0.1</button>
                            </div>

                            <div class="button-row">
                                <button id="btn-speed-reset" class="btn btn-secondary">Reset (1.0x)</button>
                                <button id="btn-speed-apply" class="btn btn-primary">Apply Speed</button>
                            </div>
                        </div>
                    </div>
                </section>
            </main>
        </div>
    </div>

    <!-- Edit Modal -->
    <div id="edit-modal" class="modal-overlay hidden">
        <div class="modal glass-modal">
            <h3>Edit Address</h3>
            <div class="address-display" id="modal-address">0x0</div>
            <div class="input-group">
                <input type="text" id="modal-input" placeholder="New value...">
            </div>
            <div class="modal-buttons">
                <button class="btn btn-secondary" id="btn-modal-cancel">Cancel</button>
                <button class="btn btn-primary" id="btn-modal-save">Modify</button>
            </div>
        </div>
    </div>

    <script>
// State Management
let currentResults = [];
let lockedAddresses = new Set();
let selectedAddress = null;
let selectedType = 'i32';

// DOM Elements
const selectType = document.getElementById('select-type');
const inputValue = document.getElementById('input-value');
const btnFirstScan = document.getElementById('btn-first-scan');
const btnNextScan = document.getElementById('btn-next-scan');
const btnClear = document.getElementById('btn-clear');
const statusText = document.getElementById('status-text');
const loader = document.getElementById('loader');
const resultsBody = document.getElementById('results-body');

const speedSlider = document.getElementById('speed-slider');
const speedVal = document.getElementById('speed-val');
const speedInput = document.getElementById('speed-input');
const speedFill = document.getElementById('speed-fill');
const btnSpeedDec = document.getElementById('btn-speed-dec');
const btnSpeedInc = document.getElementById('btn-speed-inc');
const btnSpeedReset = document.getElementById('btn-speed-reset');
const btnSpeedApply = document.getElementById('btn-speed-apply');

const editModal = document.getElementById('edit-modal');
const modalAddress = document.getElementById('modal-address');
const modalInput = document.getElementById('modal-input');
const btnModalCancel = document.getElementById('btn-modal-cancel');
const btnModalSave = document.getElementById('btn-modal-save');
const btnCloseUi = document.getElementById('btn-close-ui');

// Tab Switching
document.querySelectorAll('.nav-item').forEach(btn => {
    btn.addEventListener('click', () => {
        document.querySelectorAll('.nav-item').forEach(b => b.classList.remove('active'));
        document.querySelectorAll('.tab-content').forEach(tc => tc.classList.remove('active'));
        
        btn.classList.add('active');
        document.getElementById(btn.dataset.target).classList.add('active');
    });
});

// Helper: send message to native bridge
function sendNativeMessage(msg) {
    if (window.webkit && window.webkit.messageHandlers && window.webkit.messageHandlers.cheatEngine) {
        window.webkit.messageHandlers.cheatEngine.postMessage(msg);
    } else {
        console.log("Native message (not in iOS WKWebView):", msg);
    }
}

// Memory Scanner Actions
btnFirstScan.addEventListener('click', () => {
    const val = inputValue.value.trim();
    if (!val) return;
    
    selectedType = selectType.value;
    statusText.textContent = "Scanning memory...";
    loader.classList.remove('hidden');
    
    btnFirstScan.disabled = true;
    btnNextScan.disabled = true;
    btnClear.disabled = true;
    
    sendNativeMessage({
        action: 'firstScan',
        type: selectedType,
        value: val
    });
});

btnNextScan.addEventListener('click', () => {
    const val = inputValue.value.trim();
    if (!val) return;
    
    statusText.textContent = "Filtering results...";
    loader.classList.remove('hidden');
    
    btnFirstScan.disabled = true;
    btnNextScan.disabled = true;
    btnClear.disabled = true;
    
    sendNativeMessage({
        action: 'nextScan',
        value: val
    });
});

btnClear.addEventListener('click', () => {
    currentResults = [];
    lockedAddresses.clear();
    btnNextScan.disabled = true;
    inputValue.value = '';
    statusText.textContent = "Cleared results";
    renderResults();
    sendNativeMessage({ action: 'clear' });
});

// Speed Hack Actions
function updateSpeedUI(val) {
    speedSlider.value = val;
    speedInput.value = val;
    speedVal.textContent = parseFloat(val).toFixed(1);
    
    // Rotate speed fill gauge accordingly (max speed slider is 20, map to degrees)
    const pct = Math.min(val / 20.0, 1.0);
    const deg = -45 + (pct * 270);
    speedFill.style.transform = `rotate(${deg}deg)`;
}

speedSlider.addEventListener('input', (e) => {
    updateSpeedUI(e.target.value);
});

speedInput.addEventListener('change', (e) => {
    let val = parseFloat(e.target.value);
    if (isNaN(val) || val <= 0) val = 1.0;
    updateSpeedUI(val);
});

btnSpeedDec.addEventListener('click', () => {
    let val = parseFloat(speedInput.value) - 0.1;
    if (val < 0.1) val = 0.1;
    updateSpeedUI(val);
});

btnSpeedInc.addEventListener('click', () => {
    let val = parseFloat(speedInput.value) + 0.1;
    updateSpeedUI(val);
});

btnSpeedReset.addEventListener('click', () => {
    updateSpeedUI(1.0);
    sendNativeMessage({ action: 'setSpeed', speed: 1.0 });
});

btnSpeedApply.addEventListener('click', () => {
    const val = parseFloat(speedInput.value);
    sendNativeMessage({ action: 'setSpeed', speed: val });
});

// Close UI Overlay
btnCloseUi.addEventListener('click', () => {
    sendNativeMessage({ action: 'close' });
});

// Render results list
function renderResults() {
    resultsBody.innerHTML = '';
    
    if (currentResults.length === 0) {
        resultsBody.innerHTML = `<tr><td colspan="3" class="placeholder-row">No results.</td></tr>`;
        return;
    }
    
    currentResults.forEach(res => {
        const tr = document.createElement('tr');
        const hexAddr = '0x' + res.address.toString(16).toUpperCase();
        const isLocked = lockedAddresses.has(res.address);
        
        tr.innerHTML = `
            <td class="addr-col">${hexAddr}</td>
            <td class="val-col">${res.value}</td>
            <td class="action-cell">
                <button class="btn btn-small btn-secondary edit-btn-trigger" data-addr="${res.address}">Edit</button>
                <button class="lock-btn ${isLocked ? 'locked' : ''}" data-addr="${res.address}" data-val="${res.value}">
                    <svg viewBox="0 0 24 24">
                        ${isLocked 
                            ? '<path d="M18 8h-1V6c0-2.76-2.24-5-5-5S7 3.24 7 6v2H6c-1.1 0-2 .9-2 2v10c0 1.1.9 2 2 2h12c1.1 0 2-.9 2-2V10c0-1.1-.9-2-2-2zm-6 9c-1.1 0-2-.9-2-2s.9-2 2-2 2 .9 2 2-.9 2-2 2zm3.1-9H8.9V6c0-1.71 1.39-3.1 3.1-3.1 1.71 0 3.1 1.39 3.1 3.1v2z"/>' 
                            : '<path d="M12 17c1.1 0 2-.9 2-2s-.9-2-2-2-2 .9-2 2 .9 2 2 2zm6-9h-1V6c0-2.76-2.24-5-5-5S7 3.24 7 6h1.9c0-1.71 1.39-3.1 3.1-3.1 1.71 0 3.1 1.39 3.1 3.1v2H6c-1.1 0-2 .9-2 2v10c0 1.1.9 2 2 2h12c1.1 0 2-.9 2-2V10c0-1.1-.9-2-2-2zm0 12H6V10h12v10z"/>'
                        }
                    </svg>
                </button>
            </td>
        `;
        
        // Modal Trigger
        tr.querySelector('.edit-btn-trigger').addEventListener('click', () => {
            selectedAddress = res.address;
            modalAddress.textContent = hexAddr;
            modalInput.value = res.value;
            editModal.classList.remove('hidden');
        });
        
        // Lock Trigger
        tr.querySelector('.lock-btn').addEventListener('click', (e) => {
            const btn = e.currentTarget;
            const addr = parseInt(btn.dataset.addr);
            const val = btn.dataset.val;
            
            if (lockedAddresses.has(addr)) {
                lockedAddresses.delete(addr);
                sendNativeMessage({ action: 'unlock', address: addr });
            } else {
                lockedAddresses.add(addr);
                sendNativeMessage({ action: 'lock', address: addr, type: selectedType, value: val });
            }
            renderResults();
        });
        
        resultsBody.appendChild(tr);
    });
}

// Modal Buttons
btnModalCancel.addEventListener('click', () => {
    editModal.classList.add('hidden');
    selectedAddress = null;
});

btnModalSave.addEventListener('click', () => {
    const val = modalInput.value.trim();
    if (!val || selectedAddress === null) return;
    
    // Update local copy
    const idx = currentResults.findIndex(r => r.address === selectedAddress);
    if (idx !== -1) {
        currentResults[idx].value = val;
        // If locked, update locked value
        if (lockedAddresses.has(selectedAddress)) {
            sendNativeMessage({ action: 'lock', address: selectedAddress, type: selectedType, value: val });
        }
    }
    
    sendNativeMessage({
        action: 'modify',
        address: selectedAddress,
        type: selectedType,
        value: val
    });
    
    editModal.classList.add('hidden');
    selectedAddress = null;
    renderResults();
});

// Bridge callbacks from Native (C++)
window.onScanComplete = function(matchCount) {
    loader.classList.add('hidden');
    btnFirstScan.disabled = false;
    btnClear.disabled = false;
    
    if (matchCount > 0) {
        btnNextScan.disabled = false;
        statusText.textContent = `Found ${matchCount} matches`;
    } else {
        btnNextScan.disabled = true;
        statusText.textContent = "No matches found";
    }
};

window.updateResults = function(resultsJsonString) {
    try {
        currentResults = JSON.parse(resultsJsonString);
        renderResults();
    } catch (e) {
        console.error("Failed to parse results JSON:", e);
    }
};

window.updateLockedValues = function(lockedJsonString) {
    try {
        const lockedArray = JSON.parse(lockedJsonString);
        lockedAddresses = new Set(lockedArray);
        renderResults();
    } catch (e) {
        console.error("Failed to parse locked addresses JSON:", e);
    }
};

</script>
</body>
</html>

)html";

#endif // INLINED_HTML_HPP
