#pragma once

// C++03 互換：文字列連結で長いHTMLを定義
const char* const CHEAT_UI_HTML =
"<!DOCTYPE html>"
"<html lang=\"en\">"
"<head>"
"<meta charset=\"UTF-8\">"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
"<title>Antigravity Cheat Engine</title>"
"<style>"
":root{"
"--bg-primary:rgba(10,10,20,0.95);"
"--bg-secondary:rgba(20,20,40,0.9);"
"--accent-cyan:#00f0ff;"
"--accent-purple:#b829dd;"
"--text-primary:#e0e0ff;"
"--text-secondary:#9090b0;"
"--border-glow:rgba(0,240,255,0.3);"
"--font-main:'Segoe UI',system-ui,sans-serif;"
"--font-mono:'JetBrains Mono',monospace;"
"}"
"* { margin: 0; padding: 0; box-sizing: border-box; }"
"body {"
"font-family: var(--font-main);"
"background: var(--bg-primary);"
"color: var(--text-primary);"
"min-height: 100vh;"
"display: flex;"
"flex-direction: column;"
"padding: 20px;"
"backdrop-filter: blur(20px);"
"}"
".header {"
"text-align: center;"
"padding: 20px 0;"
"border-bottom: 1px solid var(--border-glow);"
"margin-bottom: 20px;"
"}"
".header h1 {"
"font-size: 28px;"
"font-weight: 800;"
"background: linear-gradient(135deg, var(--accent-cyan), var(--accent-purple));"
"-webkit-background-clip: text;"
"-webkit-text-fill-color: transparent;"
"text-shadow: 0 0 30px rgba(0, 240, 255, 0.3);"
"}"
".header p {"
"color: var(--text-secondary);"
"font-size: 12px;"
"margin-top: 5px;"
"letter-spacing: 2px;"
"}"
".main-content {"
"display: grid;"
"grid-template-columns: 1fr 1fr;"
"gap: 20px;"
"flex: 1;"
"}"
".panel {"
"background: var(--bg-secondary);"
"border: 1px solid var(--border-glow);"
"border-radius: 16px;"
"padding: 20px;"
"box-shadow: 0 8px 32px rgba(0, 0, 0, 0.3);"
"}"
".panel-title {"
"font-size: 14px;"
"font-weight: 700;"
"color: var(--accent-cyan);"
"margin-bottom: 15px;"
"display: flex;"
"align-items: center;"
"gap: 8px;"
"}"
".input-group {"
"display: flex;"
"flex-direction: column;"
"gap: 10px;"
"margin-bottom: 15px;"
"}"
".input-group label {"
"font-size: 12px;"
"color: var(--text-secondary);"
"font-weight: 600;"
"}"
"input, select {"
"background: rgba(0, 0, 0, 0.3);"
"border: 1px solid var(--border-glow);"
"border-radius: 8px;"
"padding: 10px 14px;"
"color: var(--text-primary);"
"font-family: var(--font-mono);"
"font-size: 13px;"
"outline: none;"
"transition: all 0.3s ease;"
"}"
"input:focus, select:focus {"
"border-color: var(--accent-cyan);"
"box-shadow: 0 0 15px rgba(0, 240, 255, 0.2);"
"}"
".btn {"
"background: linear-gradient(135deg, var(--accent-cyan), var(--accent-purple));"
"border: none;"
"border-radius: 10px;"
"padding: 12px 20px;"
"color: #000;"
"font-weight: 800;"
"font-size: 13px;"
"cursor: pointer;"
"transition: all 0.3s ease;"
"text-transform: uppercase;"
"letter-spacing: 1px;"
"}"
".btn:hover {"
"transform: translateY(-2px);"
"box-shadow: 0 8px 25px rgba(0, 240, 255, 0.4);"
"}"
".btn-secondary {"
"background: transparent;"
"border: 1px solid var(--border-glow);"
"color: var(--accent-cyan);"
"}"
".btn-secondary:hover {"
"background: rgba(0, 240, 255, 0.1);"
"}"
".results-area {"
"background: rgba(0, 0, 0, 0.2);"
"border-radius: 12px;"
"padding: 15px;"
"min-height: 200px;"
"max-height: 300px;"
"overflow-y: auto;"
"font-family: var(--font-mono);"
"font-size: 12px;"
"border: 1px solid var(--border-glow);"
"}"
".result-item {"
"display: flex;"
"justify-content: space-between;"
"align-items: center;"
"padding: 8px 12px;"
"border-radius: 6px;"
"margin-bottom: 6px;"
"background: rgba(255, 255, 255, 0.03);"
"transition: all 0.2s ease;"
"}"
".result-item:hover {"
"background: rgba(0, 240, 255, 0.05);"
"}"
".result-addr {"
"color: var(--accent-cyan);"
"font-weight: 600;"
"}"
".result-val {"
"color: var(--text-secondary);"
"}"
".result-actions {"
"display: flex;"
"gap: 6px;"
"}"
".result-actions button {"
"padding: 4px 10px;"
"font-size: 10px;"
"border-radius: 4px;"
"border: none;"
"cursor: pointer;"
"font-weight: 700;"
"}"
".btn-lock { background: var(--accent-purple); color: #fff; }"
".btn-edit { background: var(--accent-cyan); color: #000; }"
".speed-panel {"
"grid-column: 1 / -1;"
"display: flex;"
"align-items: center;"
"justify-content: space-between;"
"padding: 15px 25px;"
"}"
".speed-info {"
"display: flex;"
"align-items: center;"
"gap: 15px;"
"}"
".speed-label {"
"font-size: 13px;"
"font-weight: 700;"
"color: var(--text-secondary);"
"}"
".speed-val {"
"font-size: 24px;"
"font-weight: 800;"
"font-family: var(--font-mono);"
"color: var(--text-primary);"
"text-shadow: 0 0 10px rgba(255, 255, 255, 0.1);"
"}"
".speed-unit {"
"font-size: 12px;"
"color: var(--text-secondary);"
"margin-left: 4px;"
"}"
".speed-controls {"
"display: flex;"
"align-items: center;"
"gap: 15px;"
"}"
".slider-wrapper {"
"display: flex;"
"align-items: center;"
"gap: 10px;"
"}"
".speed-limit {"
"font-size: 11px;"
"color: var(--text-secondary);"
"font-family: var(--font-mono);"
"}"
"input[type=\"range\"] {"
"-webkit-appearance: none;"
"appearance: none;"
"width: 200px;"
"height: 6px;"
"background: rgba(0, 0, 0, 0.3);"
"border-radius: 3px;"
"outline: none;"
"}"
"input[type=\"range\"]::-webkit-slider-thumb {"
"-webkit-appearance: none;"
"appearance: none;"
"width: 20px;"
"height: 20px;"
"background: linear-gradient(135deg, var(--accent-cyan), var(--accent-purple));"
"border-radius: 50%;"
"cursor: pointer;"
"box-shadow: 0 0 15px rgba(0, 240, 255, 0.5);"
"transition: all 0.3s ease;"
"}"
"input[type=\"range\"]::-webkit-slider-thumb:hover {"
"transform: scale(1.2);"
"box-shadow: 0 0 25px rgba(0, 240, 255, 0.8);"
"}"
".status-bar {"
"display: flex;"
"justify-content: space-between;"
"align-items: center;"
"padding: 12px 20px;"
"background: rgba(0, 0, 0, 0.2);"
"border-radius: 10px;"
"margin-top: 15px;"
"font-size: 11px;"
"color: var(--text-secondary);"
"}"
".status-indicator {"
"display: flex;"
"align-items: center;"
"gap: 6px;"
"}"
".status-dot {"
"width: 8px;"
"height: 8px;"
"border-radius: 50%;"
"background: var(--accent-cyan);"
"box-shadow: 0 0 10px var(--accent-cyan);"
"animation: pulse 2s infinite;"
"}"
"@keyframes pulse {"
"0%, 100% { opacity: 1; }"
"50% { opacity: 0.5; }"
"}"
".close-btn {"
"position: absolute;"
"top: 15px;"
"right: 15px;"
"background: none;"
"border: none;"
"color: var(--text-secondary);"
"font-size: 20px;"
"cursor: pointer;"
"padding: 5px;"
"border-radius: 50%;"
"transition: all 0.3s ease;"
"}"
".close-btn:hover {"
"color: var(--accent-cyan);"
"background: rgba(0, 240, 255, 0.1);"
"}"
"</style>"
"</head>"
"<body>"
"<button class=\"close-btn\" onclick=\"window.webkit.messageHandlers.cheatEngine.postMessage({action:'close'})\">&times;</button>"
"<div class=\"header\">"
"<h1>ANTIGRAVITY</h1>"
"<p>ADVANCED CHEAT ENGINE</p>"
"</div>"
"<div class=\"main-content\">"
"<div class=\"panel\">"
"<div class=\"panel-title\">&#128269; Memory Scanner</div>"
"<div class=\"input-group\">"
"<label>Value Type</label>"
"<select id=\"type-select\">"
"<option value=\"i32\">Integer (32-bit)</option>"
"<option value=\"i64\">Integer (64-bit)</option>"
"<option value=\"float\">Float</option>"
"<option value=\"double\">Double</option>"
"</select>"
"</div>"
"<div class=\"input-group\">"
"<label>Search Value</label>"
"<input type=\"text\" id=\"search-val\" placeholder=\"Enter value...\">"
"</div>"
"<div style=\"display:flex;gap:10px;\">"
"<button class=\"btn\" onclick=\"firstScan()\">First Scan</button>"
"<button class=\"btn btn-secondary\" onclick=\"nextScan()\">Next Scan</button>"
"</div>"
"<div class=\"results-area\" id=\"results\">"
"<div style=\"text-align:center;color:var(--text-secondary);padding:40px 0;\">"
"Enter a value and click First Scan to begin"
"</div>"
"</div>"
"</div>"
"<div class=\"panel\">"
"<div class=\"panel-title\">&#128275; Locked Values</div>"
"<div class=\"results-area\" id=\"locked\">"
"<div style=\"text-align:center;color:var(--text-secondary);padding:40px 0;\">"
"No locked values yet"
"</div>"
"</div>"
"<button class=\"btn btn-secondary\" style=\"width:100%;margin-top:10px;\" onclick=\"clearResults()\">Clear All</button>"
"</div>"
"<div class=\"panel speed-panel\">"
"<div class=\"speed-info\">"
"<div class=\"speed-label\">&#9889; SPEED HACK</div>"
"<div><span class=\"speed-val\" id=\"speed-val\">1.0</span><span class=\"speed-unit\">x</span></div>"
"</div>"
"<div class=\"speed-controls\">"
"<div class=\"slider-wrapper\">"
"<span class=\"speed-limit\">0.1x</span>"
"<input type=\"range\" id=\"speed-slider\" min=\"0.1\" max=\"10\" step=\"0.1\" value=\"1\" oninput=\"updateSpeed(this.value)\">"
"<span class=\"speed-limit\">10x</span>"
"</div>"
"</div>"
"</div>"
"</div>"
"<div class=\"status-bar\">"
"<div class=\"status-indicator\">"
"<div class=\"status-dot\"></div>"
"<span>System Active</span>"
"</div>"
"<span id=\"result-count\">Results: 0</span>"
"</div>"
"<script>"
"var results = [];"
"var locked = [];"
"function firstScan() {"
"var type = document.getElementById('type-select').value;"
"var value = document.getElementById('search-val').value;"
"if(!value) return;"
"window.webkit.messageHandlers.cheatEngine.postMessage({"
"action: 'firstScan',"
"type: type,"
"value: value"
"});"
"document.getElementById('results').innerHTML = '<div style=\"text-align:center;color:var(--text-secondary);padding:40px 0;\">Scanning...</div>';"
"}"
"function nextScan() {"
"var value = document.getElementById('search-val').value;"
"if(!value) return;"
"window.webkit.messageHandlers.cheatEngine.postMessage({"
"action: 'nextScan',"
"value: value"
"});"
"}"
"function updateResults(jsonStr) {"
"try { results = JSON.parse(jsonStr); } catch(e) { results = []; }"
"renderResults();"
"}"
"function renderResults() {"
"var html = '';"
"for(var i = 0; i < results.length; i++) {"
"html += '<div class=\"result-item\">';"
"html += '<span class=\"result-addr\">0x' + results[i].address.toString(16).toUpperCase() + '</span>';"
"html += '<span class=\"result-val\">' + results[i].value + '</span>';"
"html += '<div class=\"result-actions\">';"
"html += '<button class=\"btn-lock\" onclick=\"lockValue(' + i + ')\">LOCK</button>';"
"html += '<button class=\"btn-edit\" onclick=\"editValue(' + i + ')\">EDIT</button>';"
"html += '</div></div>';"
"}"
"document.getElementById('results').innerHTML = html || '<div style=\"text-align:center;color:var(--text-secondary);padding:40px 0;\">No results found</div>';"
"}"
"function onScanComplete(count) {"
"document.getElementById('result-count').textContent = 'Results: ' + count;"
"}"
"function lockValue(idx) {"
"var val = prompt('Enter locked value:', results[idx].value);"
"if(val === null) return;"
"window.webkit.messageHandlers.cheatEngine.postMessage({"
"action: 'lock',"
"address: results[idx].address,"
"type: document.getElementById('type-select').value,"
"value: val"
"});"
"locked.push({addr: results[idx].address, val: val});"
"renderLocked();"
"}"
"function editValue(idx) {"
"var val = prompt('Enter new value:', results[idx].value);"
"if(val === null) return;"
"window.webkit.messageHandlers.cheatEngine.postMessage({"
"action: 'modify',"
"address: results[idx].address,"
"type: document.getElementById('type-select').value,"
"value: val"
"});"
"}"
"function renderLocked() {"
"var html = '';"
"for(var i = 0; i < locked.length; i++) {"
"html += '<div class=\"result-item\">';"
"html += '<span class=\"result-addr\">0x' + locked[i].addr.toString(16).toUpperCase() + '</span>';"
"html += '<span class=\"result-val\">' + locked[i].val + '</span>';"
"html += '<button class=\"btn-edit\" onclick=\"unlockValue(' + i + ')\">UNLOCK</button>';"
"html += '</div>';"
"}"
"document.getElementById('locked').innerHTML = html || '<div style=\"text-align:center;color:var(--text-secondary);padding:40px 0;\">No locked values yet</div>';"
"}"
"function unlockValue(idx) {"
"window.webkit.messageHandlers.cheatEngine.postMessage({"
"action: 'unlock',"
"address: locked[idx].addr"
"});"
"locked.splice(idx, 1);"
"renderLocked();"
"}"
"function clearResults() {"
"window.webkit.messageHandlers.cheatEngine.postMessage({action:'clear'});"
"results = [];"
"locked = [];"
"document.getElementById('results').innerHTML = '<div style=\"text-align:center;color:var(--text-secondary);padding:40px 0;\">Enter a value and click First Scan to begin</div>';"
"document.getElementById('locked').innerHTML = '<div style=\"text-align:center;color:var(--text-secondary);padding:40px 0;\">No locked values yet</div>';"
"document.getElementById('result-count').textContent = 'Results: 0';"
"}"
"function updateSpeed(val) {"
"document.getElementById('speed-val').textContent = parseFloat(val).toFixed(1);"
"window.webkit.messageHandlers.cheatEngine.postMessage({"
"action: 'setSpeed',"
"speed: parseFloat(val)"
"});"
"}"
"</script>"
"</body>"
"</html>";